
@startmindmap Stammdaten
+[#FFBBCC] Rhetorik
++ Allg. Regeln
+++_ Blickkontakt
+++_ Körpersprache
+++_ Pausen (Pausen muss man hören können)
+++_ Bildhafte Sprache (Stillmittel, Syntax)
++ Kundenbrille
+++_ Meiner Meinung nach → Was halten Sie von?
+++_ Ich glaube → Halten Sie es für möglich, dass...?
+++_ Ich zeige Ihnen wie → Für Sie gibt es folgende Möglichkeiten
+++_ Ich erlaube mir → Bitte gestatten Sie mir
+++_ Ich gebe Ihnen → Sie erhalten von mir
+++_ Wir liefern Ihnen → Sie bekommen von uns geliefert
++ Storrytelling
+++ Theme
++++_ Life Lesson
++++_ Be good to everyone
++++_ Love takes faith
+++ Setting
++++_ Time (Zeit, Tageszeit, Jahreszeit, etc.)
++++_ Location (Country, Planet, Town, Building)
++++_ Stimmung
++++_ Atmosphere
+++ Characters 
++++_ Protagonist (good guy)
++++_ Antagonist (bad guy)
++++_ People, Animals, Things, Fantasy
+++ Conflict
++++_ Problemstellung 
+++++_ Man vs. Man 
+++++_ Man vs. Nature
+++++_ Man vs. Himself
+++++_ Man vs. Society
++++_ Troubleshooting
++++_ Confliktlösung am Schluss
+++ Plot
++++_ Introduction
+++++_ Setting
+++++_ Background
+++++_ Characters
++++_ Rising Action
+++++_ Serios of actions and desicions
+++++_ Background Situations
++++_ Climax
+++++_ Consequences from desisions and actions
++++_ Falling Action
+++++_ Life after
++++_ Resolution
++ Schlagfertigkeit
+++_ **Dummstellen**
++++ akt: So tun als ob "nix verstehen" \ncon: gute Frage, beantworte ich dir gerne am Ende
+++_ **Schlaumeier**
++++ akt: Zitate, Weißheiten, Statistik \ncon: Mit dieser Statistik bin ich leider nicht vertraut
+++_ **Kleinkariert**
++++ akt: Die Details spiegeln aber das Gesamtbild nicht ab \ncon: Die Mosaik baut ja auch auf Details auf
+++_ **Persönlich**
++++ akt: Sie haben gelbe Zähne \ncon: Ich habe ja auch bei der Post gearbeitet
+++_ **Verallgemeinerung**
++++ akt: Alle Unternehmer sind Schweine \ncon: Früher wäre ich Ihrer Meinung, \n\theute habe ich dazugelernt?
+++_ **Vorurteil**
++++ akt: In dem Alter versteht man doch die Technik nicht \ncon: Genau von Ihnen habe ich diese Aussage erwartet \n\tund kann Sie versichern, dass...
+++_ **Fachidiot**
++++ akt: Fachwörterspam \ncon: Was meinen Sie mit "Fachwort"
+++_ **Zeitschändung**
++++ con: Es ist mir wichtig diesen Punkt jetzt zu behandeln.
+++_ **Wortverdehung**
++++ akt: Wörter im Mund umdrehen \ncon: Aussage noch Mal richtig stellen
+++_ **Ablenkung**
++++ akt: Themawächsel einleiten \ncon: Darüber können wir uns später unterhalten
+++_ **Entweder-Oder**
++++ Alternativen aufzeigen
+++_ **Verunsicherer**
++++ offene Fragen stellen
+++_ **Nebensächlichkeiten**
++++ ddd 
+++_ **Totschlagargumente**
+++_ **Affentaktik***
++++ akt: Oh das kann aber so nicht funktionieren \ncon: Oh, dass muss Ihnen jetzt nicht peinlich \n\tsein wenn sie nicht wissen wie das funktioniert. \n\tDafür bin ich ja da.
-- Konzepte
---_ Chronologie
---- Vergangenheit → Gegenwart → Zukunft
---_ Abwegung
---- Pro → Contra → Kompromiss
---_ Veränderung
---- Ist → Soll → Lösungsansatz
---_ Fakten
---- Ist → Ursache → Folgerung
---_ Erfahrung
---- Problemstellung → Scheinlösung bloßstellen → Eigene Lösung
---_ AIDA
---- Attention → Interest → Demand → Action
---_ Einwandhandling
---- Verständnis → Zurück zur Lösung → Referenz → Impuls
-- Stilmittel
---_ **Allegorie/Symbol**
---- Bildlicher Begriff: Herz, Senseman, Eisenhufe, Kleeblatt
---_ **Alliteration**
---- Gleiche Laute am Anfang: Alle Affen Aßen Annanas
---_ **Anapher**
---- Gleiche Laute an wiederholenden Satzanfängen \n-Ich komme auf euch zu um euch zu helfen. \n-ich komme auf euch zu um euch zu geben. \n-Ich komme auf euch zu um euch zu führen.
---_ **Epipher**
---- Gleiche Laute an wiederholenden Satzenden: \n-Ich komme um euch zu helfen \n-Ich möchte ... ermutigen um euch zu helfen \n-Ich werde ... versammeln um euch zu helfen.
---_ **Antithese**
---- Er wanderte am helligste Tag los und \nwanderte bis in die dunkelste Nacht
---_ **Paradoxon**
---- Widersprüchliche Aussagen: \nIch weiß, dass ich nichts weiß
---_ **Dysphemismus**
---- Negativdarstellung: Obdachloser --> Penner
---_ **Euphemismus**
---- Positivdarstellung: Dick --> Vollschlank
---_ **Hyperbel**
---- Übertreibung: Du bist der dümmste Mensch auf Erden
---_ **Emphase**
---- Besondere Betonnung eines Wortes: \nDas habe ich nicht von <u>DIR</u> erwartet!
---_ **Fragetechniken**
----_ offene Fragen
-----_ W-Fragen
----_ geschlosssene Fragen
-----_ Ja, Nein Fragen
----_ Informationsfragen
-----_ Was ist Ihnen wichtig?
-----_ Wofür benötigst du das?
----_ Suggestivfragen
-----_ Elegante Formulierung einer Feststellung
----_ Rhetorische Fragen
-----_ Wer glaubt denn so etwas?
-----_ Ist das wirklich die beste Lösung?
----_ Gegenfragen
-----_ Hast du bereits eine Vorstellung?
-----_ Was wäre eine Alternative dazu?
-----_ Ist das wirklich die beste Herangehensweise?
-----_ Denkst du, dass das auf Dauer funktioniert?
-----_ Warum kompliziert, wenn es auch einfach geht?
-----_ Wollten wir nicht genau das Gegenteil erreichen?
----_ Motivierungsfragen
-----_ Wie ist dir den DAS gelungen?
-----_ Können wir uns leisten es nicht zu tun?
----_ Provokation
-----_ Ist es überhaupt in der Lage …?
-----_ Warum denkst du, dass das d. beste Weg ist?
-----_ Wie passt das zu den Fakten, die wir kennen?
----_ Kontrollfragen
-----_ Was verstehe ich genau unter...?
-----_ Verstehe ich das richtig, dass ...?
---_ **Klimax**
---- Steigerung von Argumenten: Er kam, er sah, er siegte
---_ **Methaper**
---- Bildliche Darstellung: Ein Tropfen auf den heißen Stein
---_ **Neologismus**
---- Neuerfundenes bzw. Fremdword (Fanboy)
---_ **Parallelismus**
---- Gleicher Satzbau: \nDas ist ein Mensch. Die Katze ist ein Tier. Sie ist eine Frau.)
---_ **Personifikation**
---- Menschliche Eigenschaften für Gegenstand bzw. Sachverhalt:  \nMutter Natur. Die Zeit rennt
---_ **Repetitio**
---- Wiederhollungen: \n-Das sollten sie Prüfen! \n-Nach der Auslieferung wäre es sinnvoll es zu prüfen! \n-Ach ja, habe ich schon erwähnt, dass sie prüfen sollen?
---_ **Ironie**
---- Man sagt das Gegenteil als man meint
---_ **Sarkasmus**
---- Lächerlichmachung, Demütigung, Verspottung
---_ **Analogien**
---_ **Vergleich**
@endmindmap




@startmindmap Stammdaten
+[#FFBBCC] Smaltalk
++ Spontiwörter
+++_ Zwei Pfannen in die Eier hauen 
+++_ Ein Kuss ein Gruß eur Fidibus
++ Metapher 
+++_ Etwas aus dem Ärmel schütteln
+++_ Auf die lange Bank schieben
+++_ Einen Bären aufbinden
+++_ Durch die Blume pusten
@endmindmap
