
@startmindmap Stammdaten
+[#FFBBCC] Rhetorik
++ Allg. Regeln
+++_ Blickkontakt
+++_ Körpersprache
+++_ Pausen
+++_ Stilmittel (Bildhafte Sprache)
++ Konzepte
+++_ Chronologie
+++_ Abwegung
+++_ Veränderung
+++_ Fakten
+++_ Erfahrung
+++_ AIDA
+++_ Einwand
++ ANBU
+++_ Anlagegüter
+++_ Anlagegruppen
-- Stilmittel
---_ Allegorie
---- Senseman, Eisenhufe
---_ Alliteration
---- Alle Affen Aßen Annanas
---_ Anapher
---- -Ich komme auf euch zu um euch zu helfen. \n-ich komme auf euch zu um euch zu geben. \n-Ich komme auf euch zu um euch zu führen.
---_ Epipher
---_ Analogien
---_ Antithese
---- Er wanderte am helligste Tag los und wanderte bis in die dunkelste Nacht
---_ Dysphemismus
---- Obdachloser --> Penner
---_ Euphemismus
---- Dick --> Vollschlank
---_ Emphase
---- Nicht von <u>DIR</u> erwartet!
---_ Fragetechniken
----_ offene Fragen
----_ geschlosssene Fragen
----_ Informationsfragen
-----_ (Was ist Ihnen wichtig?)
-----_ (Wofür benötigen Sie ...?)
----_ Suggestivfragen
----_ Rhetorische Fragen
----_ Gegenfragen
----_ Motivierungsfragen
----_ Provokationsfragen
----_ Kontrollfragen
---_ Hyperbel
---- Übertreibung: Du bist der dümmste Mensch auf Erden
---_ Ironie
---- Man sagt das Gegenteil als man meint
---_ Klimax
---- Steigerung von Argumenten: Er kam, er sah, er siegte
---_ Methaper
---- Bildliche Darstellung: Ein Tropfen auf den heißen Stein
---_ Neologismus
---- Neuerfundenes bzw. Fremdword (Fanboy)
---_ Paradoxon
---_ Personifikation
---_ Repetitio
---_ Symbol
---_ Vergleich
---_ Sarkasmus
-- PLAN
---_ Produkte
---_ Teilhaushalte
---_ Budgets
---_ Produktsachkonten
---_ Maßnahmen
---_ Aufträge
---_ Statistische Produkte
++ SUA
+++ Steuerobjekte
++++_ Kundenakten
++++_ Abnahmestellen
++++_ Zähler
+++ Stammdaten
++++_ Abmeldegründe
++++_ Branchenverzeichnis
++++_ Nebenforderungen
++++_ Ortsteile
++++_ Straßenverzeichnis
++++_ Zahlenformate
@endmindmap


